# 本地存储与云端存储共同配置时，使用本地存储
storage:
    # 本地存储。
    local:
        root: "E:"
        bucketName:
    # 云端存储，需指定服务商及服务商提供的登录凭证
    cloud:
        strategy: QINIU # 服务商名称需取自枚举类CloudStorageStrategyEnum
        aliyun:
            domain:
            accessKeyId:
            accessKeySecret:
            bucketName:
            nameSpace:
            endPoint:
        qiniu:
            domain:
            accessKey:
            secretKey:
            bucketName:
            nameSpace:
        ypyun:
            domain:
            accessKeyId:
            accessKeySecret:
            bucketName:
            nameSpace:
