CREATE TABLE `blacklist_alipay_fan` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `alipay_fan_id` int(11) DEFAULT NULL COMMENT '外键',
  `alipay_user_id` varchar(128) DEFAULT NULL COMMENT '用户标识 trade_type=JSAPI，此参数必传，用户在主商户appid下的唯一标识。openid和sub_openid可以选传其中之一，如果选择传sub_openid,则必须传sub_appid。',
  `begin_date` date DEFAULT NULL COMMENT '起始时间',
  `end_date` date DEFAULT NULL COMMENT '结束时间',
  `created_by` int(11) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `last_modified_by` int(11) DEFAULT NULL,
  `last_modified_date` datetime DEFAULT NULL,
  `memo` varchar(255) DEFAULT NULL,
  `del_flag` tinyint(4) DEFAULT NULL,
  `is_all` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付宝支付黑名单';

CREATE TABLE `blacklist_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(50) DEFAULT NULL COMMENT '外键',
  `begin_date` date DEFAULT NULL COMMENT '起始时间',
  `end_date` date DEFAULT NULL COMMENT '结束时间',
  `created_by` int(11) NOT NULL,
  `created_date` datetime NOT NULL,
  `last_modified_by` int(11) DEFAULT NULL,
  `last_modified_date` datetime DEFAULT NULL,
  `memo` varchar(255) DEFAULT NULL,
  `del_flag` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户黑名单';

CREATE TABLE `blacklist_wechat_fan` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `wechat_fan_id` int(11) DEFAULT NULL COMMENT '外键',
  `openid` varchar(128) DEFAULT NULL COMMENT '用户标识 trade_type=JSAPI，此参数必传，用户在主商户appid下的唯一标识。openid和sub_openid可以选传其中之一，如果选择传sub_openid,则必须传sub_appid。',
  `sub_openid` varchar(128) DEFAULT NULL COMMENT '用户子标识 trade_type=JSAPI，此参数必传，用户在子商户appid下的唯一标识。openid和sub_openid可以选传其中之一，如果选择传sub_openid,则必须传sub_appid。',
  `begin_date` date DEFAULT NULL COMMENT '起始时间',
  `end_date` date DEFAULT NULL COMMENT '结束时间',
  `created_by` int(11) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `last_modified_by` int(11) DEFAULT NULL,
  `last_modified_date` datetime DEFAULT NULL,
  `memo` varchar(255) DEFAULT NULL,
  `del_flag` tinyint(4) DEFAULT NULL,
  `is_all` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='微信支付黑名单';

CREATE TABLE `check_payment_wechat_daily` (
  `id` int(11) NOT NULL COMMENT '订单ID，账单ID，与park_bill一致',
  `tenant_id` int(11) DEFAULT NULL COMMENT '租户ID',
  `park_id` int(11) DEFAULT NULL,
  `data_date` varchar(20) DEFAULT NULL,
  `pay_count` int(11) DEFAULT NULL COMMENT '支付笔数',
  `bill_count` int(11) DEFAULT NULL COMMENT '账单笔数',
  `imbalance_count` int(11) DEFAULT NULL COMMENT '差异笔数',
  `pay_fee` int(11) DEFAULT NULL COMMENT '支付金额',
  `bill_fee` int(11) DEFAULT NULL COMMENT '账单金额',
  `imbalance_fee` int(11) DEFAULT NULL COMMENT '差额',
  `status` int(11) DEFAULT NULL COMMENT '对账完成状态  0-否；1-是',
  `created_by` int(11) NOT NULL,
  `created_date` datetime NOT NULL,
  `last_modified_by` int(11) DEFAULT NULL,
  `last_modified_date` datetime DEFAULT NULL,
  `memo` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='微信支付交易流水对账日报';

CREATE TABLE `check_payment_wechat_detail` (
  `id` int(11) NOT NULL COMMENT '订单ID，账单ID，与park_bill一致',
  `tenant_id` int(11) DEFAULT NULL COMMENT '租户ID',
  `park_id` int(11) DEFAULT NULL,
  `order_no` varchar(64) DEFAULT NULL COMMENT '订单编号',
  `out_trade_no` varchar(32) DEFAULT NULL COMMENT '交易编号  商户系统内部交易订单号，要求32个字符内，只能是数字、大小写字母_-|*且在同一个商户号下唯一。',
  `transaction_id` varchar(32) DEFAULT NULL COMMENT '微信支付订单号',
  `pay_fee` int(11) DEFAULT NULL COMMENT '支付金额',
  `bill_fee` int(11) DEFAULT NULL COMMENT '账单金额',
  `imbalance_fee` int(11) DEFAULT NULL COMMENT '差额',
  `status` int(11) DEFAULT NULL COMMENT '对账状态',
  `created_by` int(11) NOT NULL,
  `created_date` datetime NOT NULL,
  `last_modified_by` int(11) DEFAULT NULL,
  `last_modified_date` datetime DEFAULT NULL,
  `memo` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='微信支付交易流水对账明细';

CREATE TABLE `check_refund_wechat_daily` (
  `id` int(11) NOT NULL COMMENT '订单ID，账单ID，与park_bill一致',
  `tenant_id` int(11) DEFAULT NULL COMMENT '租户ID',
  `park_id` int(11) DEFAULT NULL,
  `data_date` varchar(20) DEFAULT NULL,
  `refund_count` int(11) DEFAULT NULL COMMENT '退款笔数',
  `bill_count` int(11) DEFAULT NULL COMMENT '账单笔数',
  `imbalance_count` int(11) DEFAULT NULL COMMENT '差异笔数',
  `refund_fee` int(11) DEFAULT NULL COMMENT '退款金额',
  `bill_fee` int(11) DEFAULT NULL COMMENT '账单金额',
  `imbalance_fee` int(11) DEFAULT NULL COMMENT '差额',
  `status` int(11) DEFAULT NULL COMMENT '对账完成状态  0-否；1-是',
  `created_by` int(11) NOT NULL,
  `created_date` datetime NOT NULL,
  `last_modified_by` int(11) DEFAULT NULL,
  `last_modified_date` datetime DEFAULT NULL,
  `memo` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='微信退款交易流水对账日报';

CREATE TABLE `check_refund_wechat_detail` (
  `id` int(11) NOT NULL COMMENT '订单ID，账单ID，与park_bill一致',
  `tenant_id` int(11) DEFAULT NULL COMMENT '租户ID',
  `park_id` int(11) DEFAULT NULL,
  `order_no` varchar(64) DEFAULT NULL COMMENT '订单编号',
  `out_trade_no` varchar(32) DEFAULT NULL COMMENT '交易编号  商户系统内部交易订单号，要求32个字符内，只能是数字、大小写字母_-|*且在同一个商户号下唯一。',
  `out_refund_no` varchar(32) DEFAULT NULL COMMENT '商户退款单号 商户系统内部的退款单号，商户系统内部唯一，只能是数字、大小写字母_-|*@ ，同一退款单号多次请求只退一笔。',
  `transaction_id` varchar(32) DEFAULT NULL COMMENT '微信支付订单号',
  `refund_id` varchar(32) DEFAULT NULL COMMENT '微信退款单号，返回结果提供',
  `refund_fee` int(11) DEFAULT NULL COMMENT '退款金额',
  `bill_fee` int(11) DEFAULT NULL COMMENT '账单金额',
  `imbalance_fee` int(11) DEFAULT NULL COMMENT '差额',
  `status` int(11) DEFAULT NULL COMMENT '对账状态',
  `created_by` int(11) NOT NULL,
  `created_date` datetime NOT NULL,
  `last_modified_by` int(11) DEFAULT NULL,
  `last_modified_date` datetime DEFAULT NULL,
  `memo` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='微信退款交易流水对账明细';

CREATE TABLE `payment_transaction_wechat` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) DEFAULT NULL COMMENT '租户ID',
  `park_id` int(11) NOT NULL COMMENT '车场ID',
  `order_no` varchar(64) DEFAULT NULL COMMENT '订单编号',
  `out_trade_no` varchar(32) DEFAULT NULL COMMENT '交易编号  商户系统内部交易订单号，要求32个字符内，只能是数字、大小写字母_-|*且在同一个商户号下唯一。',
  `appid` varchar(32) CHARACTER SET dec8 COLLATE dec8_bin DEFAULT NULL COMMENT '公众账号ID 微信支付分配的公众账号ID（企业号corpid即为此appId）',
  `mch_id` varchar(32) DEFAULT NULL COMMENT '商户号 微信支付分配的商户号',
  `sub_appid` varchar(32) DEFAULT NULL COMMENT '子商户公众账号ID 微信分配的子商户公众账号ID，如需在支付完成后获取sub_openid则此参数必传。',
  `sub_mch_id` varchar(32) DEFAULT NULL COMMENT '子商户号 微信支付分配的子商户号',
  `openid` varchar(128) DEFAULT NULL COMMENT '用户标识 trade_type=JSAPI，此参数必传，用户在主商户appid下的唯一标识。openid和sub_openid可以选传其中之一，如果选择传sub_openid,则必须传sub_appid。',
  `sub_openid` varchar(128) DEFAULT NULL COMMENT '用户子标识 trade_type=JSAPI，此参数必传，用户在子商户appid下的唯一标识。openid和sub_openid可以选传其中之一，如果选择传sub_openid,则必须传sub_appid。',
  `transaction_id` varchar(64) DEFAULT NULL COMMENT '微信支付订单号',
  `total_fee` int(11) DEFAULT NULL COMMENT '总金额 订单总金额，只能为整数，详见支付金额',
  `fee_type` varchar(16) DEFAULT NULL COMMENT '货币类型 符合ISO 4217标准的三位字母代码，默认人民币：CNY，其他值列表详见货币类型',
  `bank_type` varchar(45) DEFAULT NULL COMMENT '付款银行',
  `cash_fee` int(11) DEFAULT NULL COMMENT '现金支付金额  现金支付金额订单现金支付金额，详见支付金额',
  `cash_fee_type` varchar(16) DEFAULT NULL COMMENT '现金支付货币类型 货币类型，符合ISO 4217标准的三位字母代码，默认人民币：CNY，其他值列表详见货币类型',
  `settlement_total_fee` int(11) DEFAULT NULL COMMENT '应结订单金额  应结订单金额=订单金额-非充值代金券金额，应结订单金额<=订单金额。',
  `trade_type` varchar(16) DEFAULT NULL COMMENT '交易类型 JSAPI 公众号支付 NATIVE 扫码支付 APP APP支付 说明详见参数规定',
  `limit_pay` varchar(32) DEFAULT NULL COMMENT '指定支付方式 no_credit--指定不能使用信用卡支付',
  `product_id` varchar(32) DEFAULT NULL COMMENT '商品ID trade_type=NATIVE，此参数必传。此id为二维码中包含的商品ID，商户自行定义。',
  `device_info` varchar(32) DEFAULT NULL COMMENT '设备号 终端设备号(门店号或收银设备ID)，注意：PC网页或公众号内支付请传"WEB"',
  `spbill_create_ip` varchar(16) DEFAULT NULL COMMENT '终端IP APP和网页支付提交用户端ip，Native支付填调用微信支付API的机器IP。',
  `body` varchar(128) DEFAULT NULL COMMENT '商品描述 商品描述交易字段格式根据不同的应用场景按照以下格式：PC网站——网站主页title名-实际商品名称，例如：腾讯充值中心-QQ会员充值；公众号——传入公众号名称-实际商品名称，例如：腾讯形象店- image-QQ公仔； H5——移动网页的主页title名-实际商品名称，例如：腾讯充值中心-QQ会员充值；线下门店——门店品牌名-城市分店名-实际商品名称，例如： image形象店-深圳腾大- QQ公仔）； APP——应用市场上的APP名字-实际商品名称，天天爱消除-游戏充值。',
  `detail` varchar(256) DEFAULT NULL COMMENT '商品详情 商品详细描述，对于使用单品优惠的商户，改字段必须按照规范上传，详见“单品优惠参数说明”',
  `attach` varchar(127) DEFAULT NULL COMMENT '附加数据 在查询API和支付通知中原样返回，该字段主要用于商户携带订单的自定义数据',
  `scene_info` varchar(256) DEFAULT NULL COMMENT '场景信息  该字段为JSON对象数据，对象格式为{"store_info":{"id": "门店ID","name": "名称","area_code": "编码","address": "地址" }}  。门店唯一标识、门店名称、门店所在地行政区划码(详见最新县及县以上行政区划代码) 、门店详细地址',
  `goods_tag` varchar(32) DEFAULT NULL COMMENT '订单优惠标记',
  `prepay_id` varchar(64) DEFAULT NULL COMMENT '预支付交易会话标识 微信生成的预支付回话标识，用于后续接口调用中使用，该值有效期为2小时',
  `code_url` varchar(64) DEFAULT NULL COMMENT '二维码链接 trade_type为NATIVE是有返回，可将该参数值生成二维码展示出来进行扫码支付',
  `status` int(11) DEFAULT NULL COMMENT '交易状态  1：创建；2：成功；3：取消；4：超时；5：失败',
  `time_start` varchar(14) DEFAULT NULL COMMENT '交易起始时间  订单生成时间，格式为yyyyMMddHHmmss，如2009年12月25日9点10分10秒表示为20091225091010。其他详见时间规则',
  `time_expire` varchar(14) DEFAULT NULL COMMENT '交易结束时间 交易失效时间，格式为yyyyMMddHHmmss，交易失效时间是针对交易编号而言的',
  `time_end` varchar(20) DEFAULT NULL COMMENT '支付完成时间 格式为yyyyMMddHHmmss，如2009年12月25日9点10分10秒表示为20091225091010。其他详见时间规则',
  `notify_url` varchar(256) DEFAULT NULL COMMENT '通知地址 接收微信支付异步通知回调地址，通知url必须为直接可访问的url，不能携带参数。',
  `return_code` varchar(16) DEFAULT NULL COMMENT '返回状态码 SUCCESS/FAIL 此字段是通信标识，非交易标识，交易是否成功需要查看result_code来判断',
  `return_msg` varchar(128) DEFAULT NULL COMMENT '返回信息 返回信息，如非空，为错误原因：签名失败;参数格式校验错误',
  `result_code` varchar(16) DEFAULT NULL COMMENT '业务结果 SUCCESS/FAIL',
  `err_code` varchar(32) DEFAULT NULL COMMENT '错误代码',
  `err_code_des` varchar(128) DEFAULT NULL COMMENT '错误代码描述',
  `notify_status` int(11) DEFAULT NULL COMMENT '回调订单支付记录状态，0-否，1，是',
  `created_by` int(11) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `last_modified_by` int(11) DEFAULT NULL,
  `last_modified_date` datetime DEFAULT NULL,
  `memo` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='微信支付交易流水';

CREATE TABLE `refund_transaction_wechat` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` int(11) DEFAULT NULL COMMENT '租户ID',
  `park_id` int(11) NOT NULL COMMENT '车场ID',
  `order_no` varchar(64) DEFAULT NULL COMMENT '订单编号',
  `out_trade_no` varchar(32) DEFAULT NULL COMMENT '交易编号  商户系统内部交易订单号，要求32个字符内，只能是数字、大小写字母_-|*且在同一个商户号下唯一。',
  `out_refund_no` varchar(64) DEFAULT NULL COMMENT '商户退款单号 商户系统内部的退款单号，商户系统内部唯一，只能是数字、大小写字母_-|*@ ，同一退款单号多次请求只退一笔。',
  `appid` varchar(32) CHARACTER SET dec8 COLLATE dec8_bin DEFAULT NULL COMMENT '公众账号ID 微信支付分配的公众账号ID（企业号corpid即为此appId）',
  `mch_id` varchar(32) DEFAULT NULL COMMENT '商户号 微信支付分配的商户号',
  `sub_appid` varchar(32) DEFAULT NULL COMMENT '子商户公众账号ID 微信分配的子商户公众账号ID，如需在支付完成后获取sub_openid则此参数必传。',
  `sub_mch_id` varchar(32) DEFAULT NULL COMMENT '子商户号 微信支付分配的子商户号',
  `transaction_id` varchar(64) DEFAULT NULL COMMENT '微信支付订单号',
  `refund_id` varchar(64) DEFAULT NULL COMMENT '微信退款单号，返回结果提供',
  `total_fee` int(11) DEFAULT NULL COMMENT '总金额 订单总金额，只能为整数，详见支付金额',
  `fee_type` varchar(16) DEFAULT NULL COMMENT '货币类型 符合ISO 4217标准的三位字母代码，默认人民币：CNY，其他值列表详见货币类型',
  `refund_fee` int(11) DEFAULT NULL COMMENT '申请退款金额  退款总金额，单位为分，只能为整数，可部分退款。详见支付金额',
  `refund_fee_type` varchar(8) DEFAULT NULL COMMENT '退款货币种类  退款货币类型，需与支付一致，或者不填。符合ISO 4217标准的三位字母代码，默认人民币：CNY，其他值列表详见货币类型',
  `cash_fee` int(11) DEFAULT NULL COMMENT '现金支付金额  现金支付金额订单现金支付金额，详见支付金额',
  `cash_refund_fee` int(11) DEFAULT NULL COMMENT '现金退款金额 现金退款金额，单位为分，只能为整数，详见支付金额',
  `settlement_total_fee` int(11) DEFAULT NULL COMMENT '应结订单金额  应结订单金额=订单金额-免充值代金券金额，应结订单金额<=订单金额。',
  `settlement_refund_fee` int(11) DEFAULT NULL COMMENT '退款金额 去掉非充值代金券退款金额后的退款金额，退款金额=申请退款金额-非充值代金券退款金额，退款金额<=申请退款金额',
  `refund_desc` varchar(80) DEFAULT NULL COMMENT '退款原因  若商户传入，会在下发给用户的退款消息中体现退款原因',
  `refund_account` varchar(30) DEFAULT NULL COMMENT '退款资金来源  仅针对老资金流商户使用 REFUND_SOURCE_UNSETTLED_FUNDS---未结算资金退款（默认使用未结算资金退款） REFUND_SOURCE_RECHARGE_FUNDS---可用余额退款',
  `status` int(11) DEFAULT NULL COMMENT '退款状态  交易状态  1：创建；2：成功；3：取消；4：超时；5：失败',
  `notify_url` varchar(256) DEFAULT NULL COMMENT '退款结果通知url 异步接收微信支付退款结果通知的回调地址，通知URL必须为外网可访问的url，不允许带参数。如果参数中传了notify_url，则商户平台上配置的回调地址将不会生效。',
  `return_code` varchar(16) DEFAULT NULL COMMENT '返回状态码 SUCCESS/FAIL 此字段是通信标识，非交易标识，交易是否成功需要查看result_code来判断',
  `return_msg` varchar(128) DEFAULT NULL COMMENT '返回信息 返回信息，如非空，为错误原因：签名失败;参数格式校验错误',
  `result_code` varchar(16) DEFAULT NULL COMMENT '业务结果 SUCCESS/FAIL',
  `err_code` varchar(32) DEFAULT NULL COMMENT '错误代码',
  `err_code_des` varchar(128) DEFAULT NULL COMMENT '错误代码描述',
  `notify_status` int(11) DEFAULT NULL COMMENT '回调订单支付记录状态，0-否，1，是',
  `created_by` int(11) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `last_modified_by` int(11) DEFAULT NULL,
  `last_modified_date` datetime DEFAULT NULL,
  `memo` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='微信支付退款流水';