server:
    port: 10000

eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://eureka_username:eureka_password@${eureka.instance.hostname}:${server.port}/eureka/

spring:
    security:
        user:
            #如不设置这段内容，账号默认是user，密码是一个随机值，该值会在启动时打印出来。
            name: eureka_username
            password: eureka_password