spring:
    application:
        name: @project.name@
    profiles:
        active: dev

eureka:
    instance:
        preferIpAddress: true
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
    client:
        enabled: true
        fetchRegistry: false
        registerWithEureka: true
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10
        server:
              waitTimeInMsWhenSyncEmpty: 0
    server:
        # see discussion about enable-self-preservation:
        # https://github.com/jhipster/generator-jhipster/issues/3654
        enableSelfPreservation: false
        registry-sync-retry-wait-ms: 500
        a-sgcache-expiry-timeout-ms: 60000
        eviction-interval-timer-in-ms: 30000
        peer-eureka-nodes-update-interval-ms: 30000
        renewal-threshold-update-interval-ms: 15000
        renewalPercentThreshold: 0.9
