spring:
    application:
        name: @project.artifactId@
    profiles:
        active: dev

eureka:
    # see org.springframework.cloud.netflix.eureka.server.EurekaServerConfigBean.class
    server:
        # see discussion about enable-self-preservation:
        # https://github.com/jhipster/generator-jhipster/issues/3654
        enable-self-preservation: false
        registry-sync-retry-wait-ms: 500
        waitTimeInMsWhenSyncEmpty: 0
        a-sgcache-expiry-timeout-ms: 60000
        eviction-interval-timer-in-ms: 30000
        peer-eureka-nodes-update-interval-ms: 30000
        renewal-threshold-update-interval-ms: 15000
        renewal-percent-threshold: 0.9
    # see org.springframework.cloud.netflix.eureka.server.EurekaDashboardProperties.class
#    dashboard:xxx
    # see org.springframework.cloud.netflix.eureka.EurekaInstanceConfigBean.class
    instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
        # see org.springframework.cloud.netflix.eureka.server.InstanceRegistryProperties.class
#        registry:xxx
    # see org.springframework.cloud.netflix.eureka.EurekaClientConfigBean.class
    client:
        enabled: true
        register-with-eureka: true
        fetch-registry: false #获取eureka服务器注册表上的注册信息，默认为true
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10

management:
    endpoints:
        web:
            exposure:
                include: "*" #对外暴露监控接口