server:
    port: 10101

eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: http://eureka_username:eureka_password@localhost:10001/eureka/
