server:
    port: 10101

eureka:
    client:
        service-url:
            defaultZone: http://localhost:10001/eureka/,http://localhost:10002/eureka/,http://localhost:10003/eureka/
    instance:
        prefer-ip-address: true