server:
    port: 10102

eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: http://eureka_username:eureka_password@localhost:10001/eureka/,http://eureka_username:eureka_password@localhost:10002/eureka/,http://eureka_username:eureka_password@localhost:10003/eureka/
